### DISCUSSION TITLE
关于 | Zi-Zi's Journey

### DISCUSSION THREAD

**Discussion by GZ-Metal-Cell** [GZ-Metal-Cell/GZ-Metal-Cell.github.io#296] [Announcements]
# 关于 | Zi-Zi's Journey

Zi-Zi's Journey

https://gz-metal-cell.github.io/about/

**Comment by promefire** [comment]
关哥牛逼

**Comment by promefire** [comment]
关哥新年快乐！！！！祝关哥新的一年快快乐乐！！！！！！！！！！！

**Comment by GZ-Metal-Cell** [comment]
> @promefire
> 关哥新年快乐！！！！祝关哥新的一年快快乐乐！！！！！！！！！！！

😍😍😍promefire new bee! 早日发 Electronics!

**Comment by promefire** [comment]
每天起床第一句，先给关哥问个好！

**Comment by promefire** [comment]
太强了金属细胞 310个人找到了这里！！！！

**Comment by promefire** [comment]
去后台把我调到311好吗 /(ㄒoㄒ)/~~

**Comment by promefire** [comment]
http://blog.gz-metal-cell.top/ 这个域名怎么寄了/(ㄒoㄒ)/~~

**Reply by GZ-Metal-Cell** [reply]
😭这个域名没有备案在福州会返回ip 127.0.0.1😭让福州的小伙伴看不到我赞美 pro 神😭于是我把域名撤了😭

**Comment by promefire** [comment]
😭神秘空间的入口变了😭

**Reply by GZ-Metal-Cell** [reply]
😭为了防止误触😭我把神秘入口调到了右边😭

**Comment by promefire** [comment]
太棒了😭Metal神😭这个打字机效果太有意思了😭有几个可能是表情的地方挂掉了😭

**Reply by GZ-Metal-Cell** [reply]
😭这个创意是我从一个叫 [promefire's jounery](https://blog.promefire.top/) 博客的首页里抄的 [typed.js](https://github.com/mattboldt/typed.js/)😭
😭“有几个可能是表情的地方挂掉了”是打字打到 emoji 的时候会出现简短的乱码？😭不太会修，需要请教牛逼的 promefire😭

**Reply by promefire** [reply]
拿来主义😭不会修😭
Metal神的打字机还能后退太强了😭

**Reply by GZ-Metal-Cell** [reply]
😭明明 pro 神的打字机也会后退😭还是 pro 神更加领先版本😭

**Reply by GZ-Metal-Cell** [reply]
😭好的😭它修好了😭

**Comment by promefire** [comment]
太谦虚了我的Metal神😭你明明精通 Ps、Pr、Ai、Ae、An   C、C++、C#、Python、HTML、CSS、Javascript 、 blender、unity、虚幻、H5 😭已经是无敌的六边形了😭

**Reply by GZ-Metal-Cell** [reply]
😭我是什么都会一点什么都没学好的小六边形😭还是 pro 神技术更胜一筹😭

**Reply by promefire** [reply]
有背景了😭好耶😭不愧是Metal神😭

**Reply by GZ-Metal-Cell** [reply]
😭摸鱼之神😭

**Reply by promefire** [reply]
欣赏Metal哥的博客叫摸鱼？😭我认为不是这样的😭我能从Metal哥的博客中学到好多😭

**Reply by GZ-Metal-Cell** [reply]
😭学到的越多😭导师捡到的学生就越鬼😭

**Reply by promefire** [reply]
关哥的技能树要加入vue😭react😭嵌入式了😭太强了关哥😭

**Reply by GZ-Metal-Cell** [reply]
😭最后还是退出游戏界了😭希望中国少了我这么一个优秀的游戏人才还能做出好的游戏来😭

**Comment by promefire** [comment]
😭最新的推文是404😭这难道是更高一级的加密😭

**Reply by GZ-Metal-Cell** [reply]
😭不应该啊，https://github.com/GZ-Metal-Cell/GZ-Metal-Cell.github.io/blob/master/2024/08/08/Plan-%E8%BF%99%E6%98%AF%E4%B8%80%E7%AF%87%E5%8A%A0%E5%AF%86%E6%8E%A8%E6%96%87~/index.html 里面明明是有东西的

**Reply by GZ-Metal-Cell** [reply]
难道是`~`这个符号的问题？😭

**Comment by promefire** [comment]
太强啦这个终端😭求教程😭

**Reply by GZ-Metal-Cell** [reply]
😭😭😭给 pro 神指条明路 Xterm.js😭😭😭剩下交给 AI 即可😭😭😭

**Reply by promefire** [reply]
😭😭😭猛猛烧token😭😭😭 ![20260814_144047_ic7sie](https://img1.promefire.top/20260814_144047_ic7sie.webp)

**Comment by promefire** [comment]
😭关哥还有测网站页面加载速度的网站😭

**Reply by GZ-Metal-Cell** [reply]
😭特意找了以前博客的数据：
```yaml
class_name: '网站测速'
class_desc: '测试网站性能如何？'
link_list:

- name: 'PageSpeed Insights'
    link: 'https://pagespeed.web.dev/'
    avatar: 'pagespeed.webp'
    descr: '测速并提供优化建议'
- name: 'Catchpoint'
    link: 'https://www.webpagetest.org/'
    avatar: 'webpagetest.webp'
    descr: '测速并提供优化建议'
- name: 'EXPERTE'
    link: 'https://www.experte.com/pagespeed'
    avatar: 'experte.webp'
    descr: '一次测试多个网页评分'
- name: '站长工具'
    link: 'https://tool.chinaz.com/sitespeed'
    avatar: 'chinaz.webp'
    descr: '为创业者提供动力'
```
